import Head from "next/head";
import Main from "@/component/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Learn React Concepts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Main />
      </main>
    </>
  );
}
